### ISSUE TITLE
External entry point

### ISSUE THREAD

**Issue by pvullioud** [joomla-projects/webservices#1]
Joomla webservices need an external entry point for at least two reasons.
### Having clean URLs.

like /api/v1/users/23

It's almost impossible to have clean REST URLs with the actual router of Joomla! We can achieve this with a good REST router. Choice of the router is an other topic.
### Not have to deal with system plugin

Some system plugins are very intrusive and can broke the API by adding some code in the input or break the routing mechanism.

We can create APIsystem plugins for people how would like to add something during the API initialization.

Any inputs on this subject are welcome :)

**Comment by garstud** [comment]
Hi Pierre ;)
I agree with the term "having clean URLs", this is important, right.
I understand the matter of potential conflicts between the URL for adressing a Webservice request and some existing plugins system that can modify the URI.

You talk about using the "system" group of plugins to design an API to be added in the initalization  process to **ensure the webservice url is reliable**, that's it ?
Can you explain this a little more ?
Why don't use a specific group for Webservices with some event dedicated to check control of the url during the initialization process ? (perhaps there is a joomla rule, i don't know, that prohibits this ?)

**Comment by betweenbrain** [comment]
I completely agree that having clean URLs is important, especially in this case. I'd even suggest that webservices in Joomla could be thought of as a separate application, and as such, provides the opportunity to use a different router. +1

I can see the potential issue with some system plugins. I'd suggest that any plugin, that is potentially triggered by webservcies, be  explicitly developed to be used with the API.

**Comment by pvullioud** [comment]
we can close this issue
see #4
