### ISSUE TITLE
PHP error in WebserviceModel

### ISSUE THREAD

**Issue by chrisdavenport** [joomla-projects/webservices#28]
In Administrator -> Components -> Webservices, edit a webservice entry, then click on Save (or Save & Close, etc.)...

PHP Catchable fatal error:  Argument 1 passed to JModelBase::setState() must be an instance of Joomla\Registry\Registry, string given, called in [joomlaRoot]/administrator/components/com_webservices/Webservices/Model/WebserviceModel.php on line 66 and defined in [joomlaRoot]/libraries/joomla/model/base.php on line 63

**Comment by fastslack** [comment]
@chrisdavenport Try applying this patch https://github.com/joomla-projects/webservices/pull/29. That issues come because current JModelForm is not compatible with the new MVC. A new FormModel is needed.

**Comment by fastslack** [comment]
@chrisdavenport this issue is already fixed i think, we can close this

**Comment by chrisdavenport** [comment]
Closing.  Thanks Matias.
