### ISSUE TITLE
Task: Write a minimal standalone application that will deliver the API

### ISSUE THREAD

**Issue by chrisdavenport** [joomla-projects/webservices#4]
Write a minimal standalone application on the Joomla Framework 2.0 that will deliver the API.
- suggested entry point will be /api/index.php
- since we don't yet have a "new MVC" design, we can just use something basic for now.
- minimal basic routing (could even be hard-wired for now).
- minimal content negotiation (or just forget it for now).
- don't worry about cache control at this stage.

Once this is accomplished the plugin can be deleted.

**Comment by fastslack** [comment]
@chrisdavenport In my opinion, i think that first we need to define the URI api like you defined here:

https://docs.google.com/document/d/1FVKGlV6BN6pu-YH2WR2pQHE3Ez7M6r7LD417GSw9ZSo/edit#heading=h.vv75wyugb3rj

i don't like to be insistent but https://github.com/chrisdavenport/j3-rest-api/tree/master/api is a very good start for this.

Things that needs to change:
1) New routing && MVC using JF 2.0
2) Connect maps with webservices admin interface and xml's

**Comment by wilsonge** [comment]
How standalone is standalone? For example do we want to import the Joomla configuration.php or are we going to have our own?

**Comment by wilsonge** [comment]
Started this: https://github.com/joomla-projects/webservices/pull/13

**Comment by chrisdavenport** [comment]
Good question.  It would make sense to import the CMS configuration.php otherwise you end up repeating some config variables in two places.  But we're going to need additional API-specific config variables and it might be best to keep those out of the CMS configuration.php.

On the other hand, the way I see this working is that the admin component allows you to configure and manage the API, but once you've set it up you could, in theory, disable or even uninstall the admin component and the API would continue working.  Moving forward to Joomla 4 we should, I think, be able to set up a system that doesn't have a site or admin application, so it's just the API application with no user interface at all.  In that case there would need to be enough of a "core" configuration that the API could function.  So maybe we should put all the config variables into a single file.

**Comment by chrisdavenport** [comment]
This is now well advanced so I'm closing this issue for now.
