### ISSUE TITLE
Cannot redeclare utf8_is_ascii()

### ISSUE THREAD

**Issue by chrisdavenport** [joomla-projects/webservices#56]
I'm getting this PHP fatal error when trying to install a web service XML file using the admin component.  I thought it might be something to do with 3.5.0, but I get the same error on 3.4.8 too.

PHP Fatal error:  Cannot redeclare utf8_is_ascii() (previously declared in /var/www/webservices/...../vendor/joomla/string/src/phputf8/utils/ascii.php:29) in /var/www/webservices/...../libraries/phputf8/utils/ascii.php on line 34, referer: http://localhost/webservices/...../administrator/index.php?option=com_webservices&view=webservices

**Comment by fastslack** [comment]
@chrisdavenport Maybe this is related. https://github.com/joomla/joomla-cms/issues/9666

**Comment by wilsonge** [comment]
Yah it is - we load two versions of phputf8 - and so conflicts happen. Happy times. Closing in favour of the CMS issue

**Comment by mbabker** [comment]
https://github.com/joomla/joomla-cms/pull/9704 deals with the last possible conflict in core of loading `libraries/phputf8` based functions from the library and https://github.com/joomla/joomla-cms/pull/9731 just proxies the whole library to the Composer space and removes the duplicated functions.
