### ISSUE TITLE
Decouple the code from the HAL format

### ISSUE THREAD

**Issue by chrisdavenport** [joomla-projects/webservices#6]
The current code is tied to HAL too closely.  We should have a HAL adapter, but equally it should be possible to write adapters for other formats, such as Uber or Siren, and just drop them in without having to change any library code.  We don't know what formats will be popular in the coming years, so we must code with the expectation that format preferences will change.

**Comment by wilsonge** [comment]
So I've started splitting this up with the app. The big thing left is to move the rendering of data out of the resource object and into the renderer

**Comment by chrisdavenport** [comment]
I think this has now been achieved.
